### ISSUE TITLE
Translation of doc

### ISSUE THREAD

**Issue by linonetwo** [beautifulinteractions/beautiful-react-hooks#69]
**Is your feature request related to a problem? Please describe.**
I would like to contribute a translation of documentation to Chinese.

**Describe the solution you'd like**
I think if `react-styleguidist` have a solution for i18n it would be great, but I've searched for a solution still no found a proper way to do so.

**Describe alternatives you've considered**
Maybe I can set up GitHub pages in my forked repo to serve translated files, and you can add a link to that github page?

Or maybe use `react-i18n`? https://github.com/styleguidist/react-styleguidist/issues/335

**Additional context**

I asked in their Gitter channel, getting no response https://gitter.im/styleguidist/styleguidist?at=5e56138d1c4f1707f8cee035

**Comment by antonioru** [comment]
Hello @linonetwo 

I am very happy to receive your contribution again, you are very welcome indeed. 

We can possibly hack react-styleguidist to find a solution but in my opinion the best thing to do - at least at the moment - is to translate the `README.md` file only, like [other libraries](https://github.com/react-hook-form/react-hook-form) have done so far.

I think it's the best thing to do, not only because it can be a huge work for you, but I don't want to put other contributors in the position of providing a Chinese translation when adding new features and hooks to the library. 

Perhaps, in a nearby feature, when we will get the version 1.0.0 we can have a proper website fully translated in all the languages, that would be nice! :) 

Also I can be able to provide the italian translation of the `README.md` as well, what do you think?
