### ISSUE TITLE
Support ES Modules

### ISSUE THREAD

**Issue by jwchang0206** [beautifulinteractions/beautiful-react-hooks#89]
**Is your feature request related to a problem? Please describe.**
I'm trying to export my React app as a component and I'm using `beautiful-react-hooks`.
Currently this library is only exported as **CommonJS** module, so it is not tree-shakable.

**Describe the solution you'd like**
Add a **ESModule** file in `rollup.config.js`. It is `format: es` in `output`.

**Comment by antonioru** [comment]
Hello @jwchang0206 
I am sorry for the late response,I've been real busy at work the last days.

I think your suggestion is a good improvement to the library, I'll fix this soon the next days but feel free to open a MR if you want.

**Comment by antonioru** [comment]
Hi @jwchang0206 
in the last release I've published the ES modules under the `dist/esm` directory. 
You can import your modules like the following:

```js 
import useSomething from 'beautiful-react-hooks/dist/esm/useSomething';
```

It is a test for the moment, so please feel free to test it and give me any possible feedback, but since I think this is a quite good improvement for the library I'm going to work to make it possible to import ES6 modules like this in future:

```js 
import useSomething from 'beautiful-react-hooks/useSomething'; // esm module
import useSomething from 'beautiful-react-hooks/cjs/useSomething'; // cjs module
```

I think you can expect a final release in a couple of weeks, I'm sorry I can't do it before.

**Comment by jwchang0206** [comment]
@antonioru I'm not sure how other OSS libraries handle this, but I've seen that it tries ES Module and then fallbacks to CommonJS nicely without worrying about the importing source path like the above.

**Comment by antonioru** [comment]
@jwchang0206 can you link one of those libraries?

**Comment by jwchang0206** [comment]
> @jwchang0206 can you link one of those libraries?

As I know of, `lodash-es` takes care of it naturally.

**Comment by antonioru** [comment]
@jwchang0206 I think I've understand what you mean and yes, it will be part of the next release

**Comment by antonioru** [comment]
@jwchang0206 
the 0.25.6 now supports ES modules, please let me know if you have any problem with that ;) 

I'm closing the issue...
